dataset_type: "qcat"
dataset_folder: "/media/mbed/internal/backup/haptr"
dataset_file: "qcat.pickle"
signal_length: 662
signal_start: 0
k_folds: 5
pick_modalities: [ 0, 1 ]
split_modalities: False
from_data: false
train_val_classes: [ 0, 1, 2, 3, 4 ]
test_classes: [ 5 ]